displayName: URLTest
testPlan: url_test.jmx
description: ''
engineInstances: 2
testId: 4c23188e-6525-4690-95b4-5b646f183028
testType: JMX
splitAllCSVs: False
failureCriteria:
- avg(response_time_ms) > 400
- percentage(error) > 10
autoStop:
  errorPercentage: 90
  timeWindow: 60
