displayName: URLTest
testPlan: url-test.json
description: ''
engineInstances: 2
testId: 4c23188e-6525-4690-95b4-5b646f183028
testType: URL
splitAllCSVs: False
failureCriteria:
- avg(response_time_ms) > 3000
- percentage(error) > 10
autoStop:
  errorPercentage: 90
  timeWindow: 60
