name: Load test

on: [workflow_dispatch]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read  # This is required for actions/checkout

env:
  RESOURCE_GROUP: az2006-rg
  LOAD_TEST_RESOURCE: myLoadTest

jobs:
  # This workflow consists of a single job called "loadtest"

  loadtest:

    runs-on: ubuntu-latest

    steps:

      #Login in your azure subscription using OpenID Connect (credentials stored as GitHub secrets in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      # Publish website to Azure App Service using CLI (WebApp)
      - name: Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: "./testconfig/config.yaml"
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE}}
          resourceGroup: ${{ env.RESOURCE_GROUP }}

      # upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: ${{github.workspace}}/loadTest
